export const actions = {
  SET_PLAYLIST: "SET_PLAYLIST",
  PLAY_SONG: "PLAY_SONG",
  GET_SONG: "GET_SONG",
  FILE_FAILED: "FILE_FAILED",
  FILE_UPLOADED: "FILE_UPLOADED",
  FILES_PROGRESS: "FILES_PROGRESS",
  DB_SETUP: "DB_SETUP",
  DB_COLLECTIONS_CREATED: "DB_COLLECTIONS_CREATED",
  DB_CREATED: "DB_CREATED",
  SET_QUERY: "SET_QUERY"
};
