export const actions = {
  PLAYLIST_SET: "PLAYLIST_SET",
  SONG_GET: "SONG_GET",
  FILE_FAILED: "FILE_FAILED",
  FILE_UPLOADED: "FILE_UPLOADED",
  FILES_PROGRESS: "FILES_PROGRESS",
  DB_SETUP: "DB_SETUP",
  DB_COLLECTIONS_CREATED: "DB_COLLECTIONS_CREATED",
  DB_CREATED: "DB_CREATED",
  QUEUE_SET: "QUEUE_SET",
  SONG_ADDED: "SONG_ADDED",
  SONG_SET: "SONG_SET",
  FILENAME_SET: "FILENAME_SET"
};
