export const actions = {
  TRACK_GET: "getTrack",
  TRACK_ADD: "addTrack",
  TRACK_SET: "setTrack",
  PLAYLIST_SET: "setPlaylist",
  FILE_FAILED: "FILE_FAILED",
  FILE_UPLOADED: "FILE_UPLOADED",
  FILES_PROGRESS: "FILES_PROGRESS",
  DB_SETUP: "DB_SETUP",
  DB_COLLECTIONS_CREATED: "DB_COLLECTIONS_CREATED",
  DB_CREATED: "DB_CREATED",
  QUEUE_SET: "QUEUE_SET",
  FILENAME_SET: "FILENAME_SET"
};
